#!/usr/bin/env bash
# Extract CPU model name.

cpu_info() {

  cpu=$(awk '/model name/ || /Processor/ { sub(/^.*: /, ""); print; exit}' /proc/cpuinfo)
    printf "%s\n" "$cpu"
} 

cpu_info

# Sample output:
# Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
# Feroceon 88FR131 rev 1 (v5l)
