#!/usr/bin/env bash
# List 172 subnet IP(s).
# Sample output: 
# 172.22.115.242/23

IP_address() {

  # IP addr show|
  # awk match eth 0-5 AND 172
  # print field 2

  IP=$(ip addr show |awk '/eth[0-5]/ && /172/ {print $2}')
    printf "%s\n" "$IP"
}

IP_address

# TODO:
# ------
# determine in use interface
# ------
# map MAC to DHCP IP?
