#!/usr/bin/env bash
# List 172 subnet IP(s).

# List all IPs
# Sample output:
# IP: 172.22.114.159 
# IP: 169.254.84.242 

IP_address() {

  IP=$(synonet --show |awk '/IP/ { sub(/^.*: /, ""); print}')
    printf "%s\n" "$IP"
}

# IP_address

# List 172 IPs
# Sample output:
# 172.22.114.159

IP_address() {

  IP=$(synonet --show |awk '/IP/ && /172/ { sub(/^.*: /, ""); print}')
    printf "%s\n" "$IP"
}

IP_address
# ifconfig -a |awk '/inet addr/ { sub(/^.*: /, ""); print $2;}' 
# -----
# ipconfig --help
# ------
# determine primary interface
# ------
# map MAC to DHCP IP?
