#!/usr/bin/env bash
# Get MAC address for onboard NIC(s).
# Desired output:
# LAN 1 001132623d3f
# LAN 2 001132623d40
# LAN 3
# LAN 4

mac_address() {
  mac=$(ifconfig -a |awk '/eth[0,1,2,3]/ && /HWaddr/ {print $1, $5}')
    printf "%s\n" "$mac"
}

mac_address

# Potentially simpler, and reusable approach:
# ifconfig -a |awk '/eth[0,1,2,3]/ && /HWaddr/ {print $1, $5}'
