#!/usr/bin/env bash
# Get MAC address for onboard NIC(s).
# Desired output:
# LAN 1 001132623d3f
# LAN 2 001132623d40
# LAN 3
# LAN 4

mac_address() {
  # ifconfig 


  mac=$(ifconfig -a |awk '/eth[0,1,2,3]/ && /HWaddr/ {print $1, $5}')
    printf "%s\n" "$mac"
}

mac_address

# Sample output
# eth0 00:11:32:92:C4:05
# eth1 00:11:32:92:C4:06
# eth2 00:11:32:92:C4:07
# eth3 00:11:32:92:C4:08

# Modern approach, but need to iterate?
# ip addr show eth1|awk '/link\/ether/ {print $2}'
# ip addr show |awk '/link\/ether/ {print $2}'

# Sample output: 
# 00:11:32:92:c4:06
