#!/usr/bin/env bash 
# Total memory (kB).
# Sample output: 930384 kB

memory() {

  # Match, then print 2nd, 3rd field of record.

  mems=$(awk '/MemTotal/ {print $2, $3}' /proc/meminfo)
  printf "%s\n" "$mems"
}

memory


