#!/usr/bin/env bash
# Total memory (gB) using kB to gB conversion. 
# For reference: https://stackoverflow.com/questions/56688874/convert-bytes-to-gb-in-each-line
# Sample output(s):
# 0.237873 gB
# 3.79939 gB
# 31.1288 gB 

memory() {

  # Awk to match, then print 2nd field (kB) of record
  # Divide parsed field by 1024 (2x)

  gB=$(awk '/MemTotal/ {print $2/1024/1024}' /proc/meminfo)
 
  printf "%s\n" "$gB gB"
}

memory
