#!/usr/bin/env bash
# Exoskeleton.

# Basic Information
#  - Server name
#  - DSM version

# Hardware
#  - Serial number
#  - Model name
#  - CPU 
#  - Total physical memory

# Network
#  - MAC address

# Time 
#  - System Time
#  - Uptime
