#!/usr/local/bin/env bash
# Synology serial no.
# Sample output:
# 1670NMN287200

serial_number() {

  # cat file

  serial=$(cat /proc/sys/kernel/syno_serial)
    printf "%s\n" "$serial"
}

serial_number
