#!/usr/local/bin/env bash
# Get Synology serial no.
# cat file
# sample output: 1670NMN287200

serial_number() {

  serial=$(cat /proc/sys/kernel/syno_serial)
    printf "%s\n" "$serial"
}

serial_number
