#!/usr/bin/env bash
# Select Synology system information.

FIELD=(
'Basic Information'
'Server name'
'DSM version'
'Hardware'
'Serial number'
'Model name'
'CPU'
'Total physical memory'
'Network'
'MAC address'
'IP address'
'Time'
'System time'
'Uptime'
)

# Print elements of array
# printf '%s\n' "${FIELD[@]}"

# Fully-qualified domain name

host() {

  host=$(hostname -f)
    printf "%s\n" "${FIELD[1]} $host"
}

main() {

  printf "%s\n" "${FIELD[0]}"
  host
}

main "$@"
