#!/usr/bin/env bash
# Synology system information.
# Sample output: 
# Basic Information
# Server name: constantinople
# DSM version: 7.1.1
# Hardware
# Serial number: 1860P5N072600
# Model name: RS18017xs+
# CPU: Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz
# Total physical memory: 0.887283 gB

# Field array.

FIELD=(
'Basic Information'
'Server name:'
'DSM version:'
'Hardware'
'Serial number:'
'Model name:'
'CPU:'
'Total physical memory:'
'Network'
'MAC address:'
'IP address:'
'Time'
'System time:'
'Uptime:'
)

# Fully-qualified domain name

host() {

  host=$(hostname -f)
    printf "%s\n" "${FIELD[1]} $host"
}

# Extract DSM product version.

dsm_version() {

  dsm=$(awk -F '"' 'NR==6 {print $2}' /etc.defaults/VERSION)
    printf "%s\n" "${FIELD[2]} $dsm"
}

# Synology serial no.

serial_number() {

  serial=$(cat /proc/sys/kernel/syno_serial)
    printf "%s\n" "${FIELD[4]} $serial"
}

# Synology model name.

model_name() {
  
  model=$(cat /proc/sys/kernel/syno_hw_version)
    printf "%s\n" "${FIELD[5]} $model"
}

# Extract CPU model name.

cpu_info() {

  cpu=$(awk '/model name/ || /Processor/ { sub(/^.*: /, ""); print; exit}' /proc/cpuinfo)
    printf "%s\n" "${FIELD[6]} $cpu"
}

# Total memory (gB) using kB to gB conversion.

memory() {

  gB=$(awk '/MemTotal/ {print $2/1024/1024}' /proc/meminfo)
    printf "%s\n" "${FIELD[7]} $gB gB"
}

# Main.

main() {

  printf "%s\n" "${FIELD[0]}"
  host
  dsm_version
  printf "%s\n" "${FIELD[3]}"
  serial_number
  model_name
  cpu_info
  memory
}

main "$@"
