#!/usr/bin/env bash
# System (current) time:
# hour:minute:second
# Sample output: 
# 14:41:54

system_time() {

  # uptime | awk print first field
		    
  systemtime=$(uptime | awk '{ print $1}')
    printf "%s\n" "$systemtime"
}

system_time
