#!/usr/bin/env bash
# uptime: days hours:minutes
# Sample output: 
# 437 days 20:07

time_up() { 

  # uptime |
  # awk strip whitespace AND commas, print columns 4,5,7
	    
  timeup=$(uptime |awk -F '[ ,]' ' {print $4, $5, $7}' )
    printf "%s\n" "$timeup"
}

time_up
