#!/usr/bin/env bash
# uptime: days hours:minutes

time_up(){ 
  # uptime
  # strip whitespace, commas. print columns 4,5,7
	    
  timeup=$(uptime |awk -F '[ ,]' ' {print $4, $5, $7}' )
    printf "%s\n" "$timeup"
}

time_up

# Sample output: 437 days 20:07
